//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web05.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web05.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có nguyên giá..
        /// </summary>
        public static string CostNullValue {
            get {
                return ResourceManager.GetString("CostNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database=misa.web05.ndhoang;.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có mã bộ phận..
        /// </summary>
        public static string DepartmentCodeNullValue {
            get {
                return ResourceManager.GetString("DepartmentCodeNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tên bộ phận..
        /// </summary>
        public static string DepartmentNameNullValue {
            get {
                return ResourceManager.GetString("DepartmentNameNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn không được vượt quá 99%.
        /// </summary>
        public static string DepreciationMaxLength {
            get {
                return ResourceManager.GetString("DepreciationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        public static string DepreciationMaxLengthNumber {
            get {
                return ResourceManager.GetString("DepreciationMaxLengthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIá trị hao mòn năm vượt quá 15 chữ số..
        /// </summary>
        public static string DepreciationValueYearMaxLength {
            get {
                return ResourceManager.GetString("DepreciationValueYearMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999999999999999.
        /// </summary>
        public static string DepreciationValueYearMaxLengthNumber {
            get {
                return ResourceManager.GetString("DepreciationValueYearMaxLengthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có mã loại tài sản..
        /// </summary>
        public static string FixedAssetCategoryCodeNullValue {
            get {
                return ResourceManager.GetString("FixedAssetCategoryCodeNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tên loại tài sản..
        /// </summary>
        public static string FixedAssetCategoryNameNullValue {
            get {
                return ResourceManager.GetString("FixedAssetCategoryNameNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản đã tồn tại trong hệ thống..
        /// </summary>
        public static string FixedAssetCodeDuplicateValue {
            get {
                return ResourceManager.GetString("FixedAssetCodeDuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản vượt quá 50 kí tự..
        /// </summary>
        public static string FixedAssetCodeMaxLength {
            get {
                return ResourceManager.GetString("FixedAssetCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có mã tài sản..
        /// </summary>
        public static string FixedAssetCodeNullValue {
            get {
                return ResourceManager.GetString("FixedAssetCodeNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản vượt quá 255 kí tự..
        /// </summary>
        public static string FixedAssetNameMaxLength {
            get {
                return ResourceManager.GetString("FixedAssetNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tên tài sản..
        /// </summary>
        public static string FixedAssetNameNullValue {
            get {
                return ResourceManager.GetString("FixedAssetNameNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host=localhost;.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ đã tồn tại trong hệ thống.
        /// </summary>
        public static string LicenseCodeDuplicateValue {
            get {
                return ResourceManager.GetString("LicenseCodeDuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa tài sản này vì đã có chứng từ phát sinh..
        /// </summary>
        public static string LicenseFixedAssetValue {
            get {
                return ResourceManager.GetString("LicenseFixedAssetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string MisaError {
            get {
                return ResourceManager.GetString("MisaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255.
        /// </summary>
        public static string NameMaxLengthNumber {
            get {
                return ResourceManager.GetString("NameMaxLengthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password= 123456.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port=3306;.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có số lượng..
        /// </summary>
        public static string QuantityNullValue {
            get {
                return ResourceManager.GetString("QuantityNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id = NDHoang;.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
